Dodat zadatak 4
z1z0v1c/learning-samples pull request #20
Opened 2018-09-07 14:39 UTC by azizovic-endava

2018-09-11 15:11 UTC, c0mmrade requested changes

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +public class Studenti {
fali ti javadoc

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +			System.out.println("Unesite broj studenata:");
Molim te tekst prebaci u konstante, mnogo je preglednije

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +			String imeStudenta = "";
Mozhesh da proglasish ime studenta kao promenjivu (tamo gde i scanner proglashavash) i ne treba ti vrednost "";

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +				System.out.println("Unesite ime " + i + ". studenta: ");
E sad vidi: 
formiranje stringa pomocu pluseva necemo koristiti. 
Znachi imamo ovde dve solucije, pa ti izaberi 
ili korisiti String.format(template_u_konstanti, i) 
ili koristiti String builder... 
Svakako ne mozhe ovako

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +				int pom = unosBroja();
gledaj da ti imena variabli bukvalno menjaju javadoc
sta je pom ?! jel moze nesto malo deskriptivnije

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +			return broj;
Hajde da ne koristimo multiple return pointe.

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +		String s = "";
? 
tvoja metoda ne prihvata ni jedan argument kao ulaznu vrednost...
Ovo uvek prolazi, chak i ako unesesh broj

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +	private static String unosString() {
Hajde da promenimo jednu od ove dve... chisto zbog snalazhenja... imash unosString() i unosStringa()

2018-09-11 15:11 UTC, c0mmrade commented on src/zadatak4/Studenti.java
> +	}
Nekako mi je logichnije da vrednost koju si uzeo od skenera prosledish metodi, a ne da pozivash ponovo skener na poslednju vrednost.

2018-09-17 10:24 UTC, BoskoNikolic requested changes

2018-09-17 10:24 UTC, BoskoNikolic commented on src/zadatak4/Studenti.java
> +			int brojStudenata = unosBrojaStudenata();;
Imas 2 ";" na kraju linije

2018-09-17 10:24 UTC, BoskoNikolic commented on src/zadatak4/Studenti.java
> +	static Scanner sc = new Scanner(System.in);
od linije 17 do linje 28: Sve konstante i promenljive bi trebalo da budu private static...

2018-09-17 10:24 UTC, BoskoNikolic commented on src/zadatak4/Studenti.java
> +				String s = unosImena();
Promeni ime promenljive u nesto sto ima vid smisla od s

2018-09-17 10:24 UTC, BoskoNikolic commented on src/zadatak4/Studenti.java
> +		String s = "";
Ime promenljive

2018-09-17 10:24 UTC, BoskoNikolic commented on src/zadatak4/Studenti.java
> +		String s = sc.next();
ime promenljive

2018-09-19 22:13 UTC, mpaunovi approved these changes
lgtm

2018-09-24 14:17 UTC, BoskoNikolic approved these changes

2018-09-25 08:09 UTC, BoskoNikolic approved these changes

2018-09-25 12:02 UTC, merged