Dodat zadatak 9
z1z0v1c/learning-samples pull request #26
Opened 2018-09-11 14:08 UTC by azizovic-endava

2018-09-17 11:08 UTC, BoskoNikolic commented on src/zadatak9/Main.java
> + * 		- Cena se racunapo principu kvadratura X zona (I zona 3000, II zona 2000, III zona 1000, IV zona 500e)
racuna po

2018-09-17 11:18 UTC, BoskoNikolic requested changes
Postoji greska u kodu. Broj Licne karte se ne ispisuje.

2018-09-17 11:18 UTC, BoskoNikolic commented on src/zadatak9/Vlasnik.java
> +		if (brojLicneKarte.matches("[0-9]+") && jmbg.length() == 9)
valjda brojLicneKarte.length  ?

2018-09-17 11:18 UTC, BoskoNikolic commented on src/zadatak9/Vlasnik.java
> +		if (imeIPrezime.matches("^[a-zA-Z]+[\\-'\\s]?[a-zA-Z ]+$"))
Uvedi konstatu za regex

2018-09-17 11:18 UTC, BoskoNikolic commented on src/zadatak9/Vlasnik.java
> +		if (jmbg.matches("[0-9]+") && jmbg.length() == 13)
Uvedi konstantu za regex

2018-09-17 11:18 UTC, BoskoNikolic commented on src/zadatak9/Vlasnik.java
> +		if (brojLicneKarte.matches("[0-9]+") && jmbg.length() == 9)
brojLicneKarte.length()

2018-09-19 22:25 UTC, mpaunovi requested changes

2018-09-19 22:25 UTC, mpaunovi commented on src/zadatak9/Vlasnik.java
> +			this.jmbg = "0000000000000";
Namesti da nije moguce inicijalizovati objekat tipa Vlasnik ukoliko parametri nisu dobri. Tako kreirani objekti, sa losim vrednostima nemaju nikakvu f-ju.

2018-09-19 22:25 UTC, mpaunovi commented on src/zadatak9/Vlasnik.java
> +			this.jmbg = "0000000000000";
nevalidan jmbg, hvataj exception ukoliko su nevalidne vrednosti za sve

2018-09-19 22:25 UTC, mpaunovi commented on src/zadatak9/Vlasnik.java
> +			this.brojLicneKarte = "000000000";
nema smisla

2018-09-19 22:25 UTC, mpaunovi commented on src/zadatak9/Nekretnina.java
> +			this.zona = 4;
zasto default 4?

2018-09-19 22:25 UTC, mpaunovi commented on src/zadatak9/Nekretnina.java
> +			this.kvadratura = 0;
0?

2018-09-24 07:04 UTC, mpaunovi approved these changes

2018-09-24 14:19 UTC, BoskoNikolic commented on src/zadatak9/Main.java
> + * <<<<<<< HEAD Kreirati projekat Nekretnina na sledeci nacin: - Apstraktna
Ovde kao da ti neki merge nije prosao kako treba, imas malo djubreta u ovom zaglavlju 
<<<<<<< HEAD 
. ======= 
>>>>>>> 86aabac85a89a79ded40c1bf7c535d33d76db343

2018-09-24 14:20 UTC, BoskoNikolic requested changes
ocisti java doc

2018-09-24 14:42 UTC, BoskoNikolic approved these changes

2018-09-24 14:47 UTC, merged