Dodat zadatak 10
z1z0v1c/learning-samples pull request #27
Opened 2018-09-11 14:15 UTC by azizovic-endava

2018-09-13 20:48 UTC, mpaunovi commented on src/zadatak10/Firma.java
> +		super();
zasto super()?

2018-09-13 20:48 UTC, mpaunovi commented on src/zadatak10/Kafa.java
> +		return this.getCenaProizvoda() * 1.08;
umesto 1.08 definisi konstantu

2018-09-13 20:48 UTC, mpaunovi commented on src/zadatak10/Proizvod.java
> +		super();
super?

2018-09-13 20:48 UTC, mpaunovi commented on src/zadatak10/Kafa.java
> +		return new StringBuilder(super.toString()).append(", samlevena: ").append(samlevena).append(". UKUPNA CENA PROIZVODA: ").append(getUkupnaCenaProizvoda()).toString();
probaj ovako nesto da ubacis ->  ... (samlevena) ? "mlevena":"u zrnu" ...

2018-09-13 20:48 UTC, mpaunovi commented on src/zadatak10/Meso.java
> +		return this.getCenaProizvoda() * 1.08;
konstanta

2018-09-13 20:48 UTC, mpaunovi commented on src/zadatak10/Proizvod.java
> +		super();
?

2018-09-13 20:48 UTC, mpaunovi commented on src/zadatak10/Sok.java
> +		return this.getCenaProizvoda() * 1.2;
konstanta

2018-09-17 10:12 UTC, BoskoNikolic requested changes

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Firma.java
> +	private ArrayList<Proizvod> listaProizvoda;
Koristi List<Proizvod> umesto ArrayList<Priozvod>

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Firma.java
> +	public Firma(double kapital, ArrayList<Proizvod> listaProizvoda) {
isto kao linija 14.

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Main.java
> +		ArrayList<Proizvod> lista1 = new ArrayList<>();
List<Proizvod> lista1 = new ArrayList<>();

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Main.java
> +		ArrayList<Proizvod> lista2 = new ArrayList<>();
List<Proizvod> lista2 = new ArrayList<>();

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Firma.java
> +			System.out.println(new StringBuilder("Lista proizvoda: ").append(this.listaProizvoda));
Gleadaj da ne stampas sve u jednoj linije, posto je izuzetno necitljivo.

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Firma.java
> +			System.out.println(new StringBuilder("Lista proizvoda: ").append(this.listaProizvoda));
isto kao linija 30

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Firma.java
> +	public Firma(double kapital, ArrayList<Proizvod> listaProizvoda) {
Moze da bude package-private

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Firma.java
> +	public void porudzbina() {
Moze da bude package-private

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Kafa.java
> +	public Kafa(String imeProizvoda, double cenaProizvoda, String rokTrajanja, boolean samlevena) {
Moze da bude package-private

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Meso.java
> +	public Meso(String imeProizvoda, double cenaProizvoda, String rokTrajanja, String zivotinjskoPoreklo) {
Moze da bude package-private

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/MlecniProizvod.java
> +	public MlecniProizvod(String imeProizvoda, double cenaProizvoda, String rokTrajanja, String porekloMleka) {
Moze da bude package-private

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Proizvod.java
> +	protected Proizvod() {
Moze da bude package-private

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Proizvod.java
> +	protected Proizvod(String imeProizvoda, double cenaProizvoda, String rokTrajanja) {
Moze da bude package-private

2018-09-17 10:12 UTC, BoskoNikolic commented on src/zadatak10/Sok.java
> +	public Sok(String imeProizvoda, double cenaProizvoda, String rokTrajanja, String sastav) {
Moze da bude package-private

2018-09-19 22:27 UTC, mpaunovi approved these changes

2018-09-22 06:26 UTC, BoskoNikolic approved these changes

2018-09-24 08:17 UTC, merged