Dodat zadatak 12
z1z0v1c/learning-samples pull request #33
Opened 2018-09-13 15:06 UTC by azizovic-endava

2018-09-14 10:37 UTC, BoskoNikolic commented on src/zadatak12/Student.java
> +	public int compareTo(Student o) {
Promenljiva naziv promenljive "o" nema nikakog smisla i cini kod necitljivim. Promeni je u nesto citljivije.

2018-09-17 11:00 UTC, BoskoNikolic requested changes

2018-09-17 11:00 UTC, BoskoNikolic commented on src/zadatak12/Main.java
> + * Kao r4ezultat programa,  ocekuje se izlazni fiajl "ocene.txtx" u kome ce se nalaziti lista
imas typo na par mesta  : "r4ezultat:   "fiajl"  "ocene.txtx"  "od najvise ka najmanje" " koju je dobio na ispiti"  "Ocena 10 akoje"

2018-09-17 11:00 UTC, BoskoNikolic commented on src/zadatak12/Main.java
> +				break;
Meni licno je jako ruzno vrteti se u petlji kojoj je uslov uvek true i onda uraditi break. Mozda je bilo bolje da si nako sto setujes broj poena studenta (linija 50), pitao "Unesi X za prekid, ili tako nesto, i onda postavio vrednost boolen-a "nastavi" na false (kad si ga vec uveo). 

if (ime.equalsIgnoreCase("x"))
				nastavi=false;

2018-09-17 11:00 UTC, BoskoNikolic commented on src/zadatak12/Main.java
> +		String s = "";
Ime promenljive

2018-09-17 11:00 UTC, BoskoNikolic commented on src/zadatak12/Student.java
> +	public int compareTo(Student o) {
Cisto za vezbu, ne moras da menjas, da li uspeo da napises ovu metodu koristeci ? : operatore ?

2018-09-19 23:05 UTC, mpaunovi commented on src/zadatak12/Main.java
> +	private static final String REGEX = "[a-zA-Z]+";
prosiri regex, ne moze da se unese ime i prezime, a da izmedju bude razmak. Postoje prezimena sa apostrofom (April O'Neil) koja kod tebe nece raditi.

2018-09-19 23:05 UTC, mpaunovi commented on src/zadatak12/Main.java
> +		try {
probaj da implementiras try-with-resources

2018-09-19 23:05 UTC, mpaunovi commented on src/zadatak12/Main.java
> +		String imeIPrezime = "";
nema potrebe dodeljivati prazan string

2018-09-25 08:08 UTC, BoskoNikolic approved these changes

2018-09-25 08:10 UTC, merged